# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: 'gmagick'
    twig:
        mode: lazy
    webp:
        generate: true
        quality: 100
        cache: ~
    messenger: true
    controller:
        redirect_response_code: 301

    filter_sets:
        cache: ~

        # Avatar small
        avatar_small:
            quality: 80
            filters:
                thumbnail:
                    size: [48, 48]

        # Avatar
        avatar:
            quality: 80
            filters:
                thumbnail:
                    size: [200, 200]

        # List
        short_list:
            quality: 100
            filters:
                thumbnail:
                    size: [24, 24]
                    mode: outbound

        # Tech picture
        tech_picture:
            quality: 90
            filters:
                thumbnail:
                    size: [200, 200]

        tech_picture_side:
            quality: 90
            filters:
                thumbnail:
                    size: [64, 64]
