templates:
 # Generate twig template for icon
 i-twig:
  from: "./.dahl/create-icon/icon.twig.dahl"
  to: "./templates/icon"
  suffix: ".html"
  extension: ".twig"

 # Generate yml file for translation
 trans:
  from: "./.dahl/create-translation/translation.yml.dahl"
  to: "./translations"
  extension: ".yaml"

 # Generate class for component
 c-class:
  from: "./.dahl/create-component/component.class.dahl" 
  suffix: "Component"
  extension: ".php"

 # Generate twig template for component
 c-twig:
  from: "./.dahl/create-component/component.twig.dahl"
  suffix: ".html"
  extension: ".twig"

 a-controller:
  from: "./.dahl/create-admin/admin-controller.dahl"
  to: "./src/Controller/Admin"
  suffix: "Controller"
  extension: ".php"

 a-template:
  from: "./.dahl/create-admin/admin-template.dahl"
  filename: "index"
  suffix: ".html"
  extension: ".twig"

 a-form-edit:
  from: "./.dahl/create-admin/edit/admin-form-edit.twig.dahl"
  filename: "edit"
  suffix: ".html"
  extension: ".twig"

 a-form-content:
  from: "./.dahl/create-admin/edit/admin-form-content.twig.dahl"
  filename: "_edit_content"
  suffix: ".html"
  extension: ".twig"

 a-form-delete:
  from: "./.dahl/create-admin/edit/admin-form-delete.twig.dahl"
  filename: "_delete_form"
  suffix: ".html"
  extension: ".twig"
  
 a-form:
  from: "./.dahl/create-admin/edit/admin-form.twig.dahl"
  filename: "_form"
  suffix: ".html"
  extension: ".twig"
  
